# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Henrique Silva
email: henrique@dryworks.com.br
description: > # this means to ignore newlines until "baseurl:"
  "Se vi mais longe foi por estar de pé sobre ombros de gigantes."
  - Isaac Newton -
baseurl: "henriquehsilva.github.io/henriquesilvadev" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
github_username:  henriquehsilva

# Gems settings
plugins: [jekyll-paginate]

# Build settings
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  syntax_highlighter: orange
paginate: 5
