[build]
  base = "."
  command = "npm install && rm -rf node_modules/@lekoarts && cp -rf @lekoarts node_modules/ && rm -rf -rf node_modules/gatsby-plugin-sitemap && cp -rf gatsby-plugin-sitemap node_modules/ && yarn build"
  publish = "public"
